name: email_sender
description: Email Sender simplifies email integration in Flutter, enabling users to send emails, facilitate OTP verification, Enhance your app's email functionality effortlessly.
version: 1.1.4
homepage: https://github.com/afriddev
repository: https://github.com/afriddev/email_sender

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  requests: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: